# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "reseller-plugin-new"
client_id = "174a87b2c7f391cc0475f9d3b9bb36a5"
application_url = "https://episodes-politicians-scores-dept.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_customers,write_products,read_customers,unauthenticated_read_customers,unauthenticated_write_customers"

[auth]
redirect_urls = [
  "https://episodes-politicians-scores-dept.trycloudflare.com/auth/callback",
  "https://episodes-politicians-scores-dept.trycloudflare.com/auth/shopify/callback",
  "https://episodes-politicians-scores-dept.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "soundboxdev.myshopify.com"
