# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "plugin-reseller"
client_id = "9d6756a6acbf5c4ec6899f845be8ef8d"
application_url = "https://soundboxstore-shopify-plugin-trade-customer-manager.x67nf4.easypanel.host"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_customers,write_products,read_customers,unauthenticated_read_customers,unauthenticated_write_customers"

[auth]
redirect_urls = [
  "https://soundboxstore-shopify-plugin-trade-customer-manager.x67nf4.easypanel.host/auth/callback",
  "https://soundboxstore-shopify-plugin-trade-customer-manager.x67nf4.easypanel.host/auth/shopify/callback",
  "https://soundboxstore-shopify-plugin-trade-customer-manager.x67nf4.easypanel.host/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "soundboxdev.myshopify.com"
