# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "reseller-plugin"
client_id = "1523c0c56a71628036f3ca94863120fc"
application_url = "https://shopify-plugin-reseller-manager.hieunguyen.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_customers,write_products,read_customers,unauthenticated_read_customers,unauthenticated_write_customers"

[auth]
redirect_urls = [
  "https://shopify-plugin-reseller-manager.hieunguyen.dev/auth/callback",
  "https://shopify-plugin-reseller-manager.hieunguyen.dev/auth/shopify/callback",
  "https://shopify-plugin-reseller-manager.hieunguyen.dev/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "soundboxdev.myshopify.com"
